### ISSUE TITLE
No Beige Book for 2020

### ISSUE THREAD

**Issue by mdayoub493** [David-Woroniuk/FedTools#1]
Hello, I have installed the Fedtools package but, for the Beige Book, it is not getting the data for 2020. It gets from 1996 to 2019, skips 2020, and then gets 2021. Do you know what is wrong and how can I fixed it, please?

**Comment by David-Woroniuk** [comment]
Hello mdayoub493,

Please note that you can edit the default arguments to achieve this. Please edit the default argument ```historical_split``` to ```2020``` instead of ```2019``` as below:

```python
beige_books = BeigeBooks(
            main_url = 'https://www.federalreserve.gov', 
            beige_book_url='https://www.federalreserve.gov/monetarypolicy/beige-book-default.htm',
            historical_split = 2020,
            verbose = True,
            thread_num = 10)
            
            
dataset = beige_books.find_beige_books()
dataset.tail(20)
```
