### ISSUE TITLE
FED website returning 403 error for requests without user agent

### ISSUE THREAD

**Issue by Marigold** [David-Woroniuk/FedTools#3]
FED have started blocking requests without user agent with 403 error. This snippet

```
from FedTools import FederalReserveMins
FederalReserveMins(historical_split=2016).find_minutes()
```

raises

```
HTTPError: HTTP Error 403: Forbidden
```

This could be easily fixed by adding random UA with e.g. https://pypi.org/project/fake-useragent/. Here's an example that patches `urlopen` and works. This is obviously a hackish solution, we'd ideally replace `urlopen` in all modules.

```
from fake_useragent import UserAgent
from urllib.request import Request, urlopen

from FedTools import FedMins
from FedTools import FederalReserveMins

def urlopen_with_ua(url):
    ua = UserAgent()
    req = Request(url)
    req.add_header("user-agent", ua.chrome)
    return urlopen(req)

FedMins.urlopen = urlopen_with_ua

FederalReserveMins(historical_split=2016).find_minutes()
```

**Comment by David-Woroniuk** [comment]
Thanks for reporting, working on a refactor for the library.

**Comment by David-Woroniuk** [comment]
Fixed, new distribution available on PyPI at: https://pypi.org/project/Fedtools/0.0.6/  

Thanks for the flag and helpful suggestions @Marigold
